### Get all products without auth token should return 200
GET http://localhost:8080/api/products

?? status == 200
{{
const assert = require("assert")

const body = JSON.parse(response.body)

assert.ok(body.total >= 0)
assert.ok(body.page >= 0)
assert.ok(body.size >= 0)
assert.ok(body.totalPages >= 0)
assert.ok(body.items?.length >= 0)
}}

### Login with user1 credentials should return 200
POST http://localhost:9099/identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=gomor-e-commerce
Content-Type: application/json

{
    "email": "user1@test.com",
    "password": "S3cr3tP@ssw0rd",
    "returnSecureToken": true
}

?? status == 200
{{
const body = JSON.parse(response.body)
$global.idToken = body.idToken;
$global.refreshToken = body.refreshToken;
}}

### Get all products with auth token should return 200
GET http://localhost:8080/api/products
Authorization: Bearer {{$global.idToken}}

?? status == 200
{{
const assert = require("assert")

const body = JSON.parse(response.body)

assert.ok(body.total >= 0)
assert.ok(body.page >= 0)
assert.ok(body.size >= 0)
assert.ok(body.totalPages >= 0)

assert.ok(body.items?.length >= 0)

}}

### Get products brands without auth token should return 200
GET http://localhost:8080/api/products/brands

?? status == 200
