name: gomor-e-commerce
services:
  mongo:
    image: mongo:8
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD:-password}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME:-gomor-e-commerce}
    volumes:
      - ./compose-files/mongo:/docker-entrypoint-initdb.d
